import {
  Atom,
  BookHeart,
  BookMarked,
  BookOpen,
  Calculator,
  ChessKnight,
  ClipboardCheck,
  Code,
  Dna,
  Dumbbell,
  FlaskConical,
  Globe,
  GraduationCap,
  HeartHandshake,
  Landmark,
  Languages,
  Lightbulb,
  Mic,
  Microscope,
  MonitorPlay,
  Music,
  Newspaper,
  Palette,
  Radio,
  Scale,
  Telescope,
  type LucideIcon,
} from "lucide-react";

// O campo `icon` das disciplinas guarda o nome do ícone do Lucide (ex.: "Calculator")
export const DISCIPLINE_ICONS: Record<string, LucideIcon> = {
  Atom,
  BookHeart,
  BookMarked,
  BookOpen,
  Calculator,
  ChessKnight,
  ClipboardCheck,
  Code,
  Dna,
  Dumbbell,
  FlaskConical,
  Globe,
  HeartHandshake,
  Landmark,
  Languages,
  Lightbulb,
  Mic,
  Microscope,
  MonitorPlay,
  Music,
  Newspaper,
  Palette,
  Radio,
  Scale,
  Telescope,
};

export function getDisciplineIcon(name: string): LucideIcon {
  return DISCIPLINE_ICONS[name] ?? GraduationCap;
}
