// Títulos das lives publicadas com título genérico ("[LIVE] Aula no Minecraft"),
// transcritos da miniatura de cada vídeo, que traz a matéria e quase sempre o tema.
// Usados no lugar do título do YouTube para exibir e para classificar a aula
// (ver displayTitle em youtube-aulas.mjs). Para incluir outra live, adicione
// "<id do vídeo>": "Aula de <Matéria> no Minecraft - <tema>".
//
// Ficaram de fora 10 lives cuja miniatura não tem texto (só o logo ou o IP do servidor).

export const THUMBNAIL_TITLES = {
  TiH3te84o4A: "Aula de Física no Minecraft - Ogivas Nucleares",
  FsCH1CFRljE: "Aula de Matemática no Minecraft - Análise e construção de gráficos com números negativos",
  "9RJ01334NCs": "Aula de Geografia no Minecraft",
  cxSsdvKKqxQ: "Aula de Química no Minecraft - Teoria estrutural do carbono: postulados de Kekulé-Couper II",
  "YyQOAz-7nU4": "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  hn1b74TRs_o: "Aula de Física no Minecraft - Vetores: subtração (aula 3.2)",
  cK1FepBYQwk: "Aula de Astronomia no Minecraft - Formação planetária",
  v04NeDmAkI8: "Aula de Geografia no Minecraft",
  eQaEi2Uk4X8: "Aula de Química no Minecraft - Forças de adesão e coesão",
  pL_7rJx7n38: "Aula de Ensino Religioso no Minecraft - Demonologia no Cristianismo",
  NBdmC7i0a9A: "Aula de Física no Minecraft - Velocidade instantânea",
  a5YMrJmAzYs: "Aula de Física no Minecraft - Modelo Padrão das partículas elementares",
  xU67YJAUbMs: "Aula de Geografia no Minecraft",
  "-yfQ8uXUt9c": "Aula de Química no Minecraft - Ácidos e bases",
  A1y07Xwohbw: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  F6iBrH_Teqs: "Aula de Física no Minecraft - Energia nuclear",
  K_sa3kRAgIc: "Aula no Minecraft - Autismo: Transtorno do Espectro Autista (TEA)",
  r2lp0q0BemE: "Aula no Minecraft - Superdotação, altas habilidades e TDAH",
  "i7qAwE-IVvk": "Aula de Astrofísica no Minecraft - Gravitação",
  "7vrixX_WR5w": "Aula de Matemática no Minecraft - Matemática básica: conjuntos",
  "7ecC0vZRsWo": "Aula de Ensino Religioso no Minecraft - As parábolas contadas por Jesus",
  wYKWwWURy4c: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  "m95n4m-_Htc": "Aula de Química no Minecraft",
  ht6uk5tAMwI: "Aula de Física no Minecraft - Relatividade geral e a solução de Schwarzschild",
  LD2Gduhl2Dc: "Aula de Geografia no Minecraft",
  u_9dM2SDIeM: "Aula no Minecraft - ENEM",
  Mz0hhU6nEWk: "Aula de Português no Minecraft",
  "6_vaoOb0u7M": "Aula de Astronomia no Minecraft - Saturno e satélites",
  FySa7fgVX0E: "Aula de Ciências no Minecraft - Vulcões",
  _gHXDTur1bk: "Aula de Matemática no Minecraft - Operação básica: divisão",
  "4mvPW_rTsCs": "Aula de Ensino Religioso no Minecraft - As 5 principais religiões do mundo",
  "6D-hICrHlfk": "Aula de Português no Minecraft",
  "3oHO-WsBje0": "Aula de Geografia no Minecraft",
  "16KBwMGk4OI": "Aula de Matemática no Minecraft",
  DBXaMDxJLxA: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  "96un-KbC068": "Aula de Biologia no Minecraft - Química da vida: ácidos nucleicos",
  JSQjFjciBeY: "Aula de Geografia no Minecraft",
  wZ3AnRloexs: "Aula de Matemática no Minecraft",
  "1ZTOR8bmeaA": "Aula de Biologia no Minecraft - Hereditariedade",
  T9sFe0kMwvk: "Aula de Biologia no Minecraft - Hereditariedade",
  EGb443S5a40: "Aula de Geografia no Minecraft",
  VX5Sm2AQ7eA: "Aula de Astronomia no Minecraft - Estrelas de nêutrons e buracos negros",
  vvayaCt7UAs: "Aula de Ensino Religioso no Minecraft - A Bíblia e a inteligência artificial",
  dDgCL6ELGvY: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  AD69fDrWMy0: "Aula de Ciências no Minecraft - Aves brasileiras",
  FjQcv5dpDys: "Aula de Astronomia no Minecraft - Planeta Terra",
  QAPv0QwL6Ag: "Aula de Matemática no Minecraft",
  p6fUIUIHUqI: "Aula de Matemática no Minecraft",
  "3jbKKtpcV3c": "Aula de Português no Minecraft",
  wAfuDuD8WtY: "Aula de Matemática no Minecraft - Matemática básica: produtos notáveis",
  khi1DV0XIWk: "Aula de Xadrez no Minecraft - Aula 01",
  qO8ZjkZy_jw: "Aula de Ensino Religioso no Minecraft - Amar ao próximo como a si mesmo",
  UVAObLIRDDY: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  ARntRxJm1P4: "Aula de Literatura no Minecraft - Romantismo",
  SXezhqcEir8: "Aula de Física no Minecraft - Trocas de calor: condução, convecção e irradiação",
  kgexKMTyKTQ: "Aula de Geografia no Minecraft",
  G02fUpqDA6E: "Aula de Matemática no Minecraft - Análise e construção de gráficos com números negativos",
  MDqDd6UG_r4: "Aula de Português no Minecraft",
  "FxX2p0-avJE": "Aula de Astronomia no Minecraft - Planeta Marte",
  r8psWOF4p4w: "Aula de Geografia no Minecraft",
  F98DrSzMLsc: "Aula de Matemática no Minecraft",
  JA2y7g8iYXE: "Aula de Português no Minecraft",
  eX3awawIQPA: "Aula de Física no Minecraft - Max Planck",
  npZEkYCdhc8: "Aula de Biologia no Minecraft - Características dos seres vivos: metabolismo e homeostase",
  mBhS9FtRvRM: "Aula de Matemática no Minecraft - Tratamento da informação: os gráficos e sua representação correta",
  "9dmm_e7EUn4": "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  b_MFlLBSZVk: "Aula de Português no Minecraft",
  "S-mjDSVwsAU": "Aula de Geografia no Minecraft",
  WoYtd9wtbVE: "Aula de Matemática no Minecraft",
  qONaBbtDsJo: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  "7hswaAfbXII": "Aula de Português no Minecraft",
  D4i1RIxl5XQ: "Aula de Geografia no Minecraft",
  "6P-d7-0KuPo": "Aula de Literatura no Minecraft - Romantismo",
  B8PnHmAKK4w: "Aula de Astronomia no Minecraft - Planeta Vênus",
  hhCKSDS9QXs: "Aula de Geografia no Minecraft",
  "5t3lYiDiDfQ": "Aula de Matemática no Minecraft - Equações e soluções (parte 1)",
  "1paeXDBMt7I": "Aula de Literatura no Minecraft - Romantismo",
  IVCQq2urFrg: "Aula de Astronomia no Minecraft - Estrelas de nêutrons e buracos negros",
  kfawc3TvRMc: "Aula de Geografia no Minecraft",
  eA0Ma8OoULI: "Aula de Matemática no Minecraft - Função afim: equação da reta",
  "3T4aF7jaaPw": "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  "0aw1hM6k9Kw": "Aula de Português no Minecraft",
  "6aWh87SkpnI": "Aula de Química no Minecraft",
  "-bQHTwJ0QQg": "Aula de Geografia no Minecraft",
  GiMlv5JBxT8: "Aula de Biologia no Minecraft - Vírus: viroses associadas ao mosquito Aedes aegypti",
  ta2GkKe4794: "Aula de Física no Minecraft - Aplicação da 2ª lei: dinâmica",
  "LaDQSj2-txo": "Aula de Matemática no Minecraft",
  "9ImCo_YBMPI": "Aula de Matemática no Minecraft",
  LReOO4dhEzA: "Aula de Ciências no Minecraft - Sistema endócrino: estrutura e funcionamento",
  "vzwnA1N8y-k": "Aula de Português no Minecraft",
  Ot_FHjaYgdI: "Aula de Astronomia no Minecraft - Formação planetária",
  F2_cF3yLSGs: "Aula de Geografia no Minecraft",
  ZLZPxGtVhtA: "Aula de Ciências no Minecraft - O que é a luz?",
  PbJHZvFF55w: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  "64JUhRQvz3s": "Aula de Português no Minecraft",
  "-ug1vUkSTkA": "Aula de Matemática no Minecraft",
  ZB64jsruxXk: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  qyiqyH9ymCY: "Aula de Matemática no Minecraft",
  U90x3JopkZY: "Aula de Português no Minecraft",
  fTDSZ2EbLoc: "Aula de Biologia no Minecraft - Química da vida: carboidratos",
  "Sz2S-1gTthA": "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  B5d6Gf3wzE0: "Aula de Matemática no Minecraft - Operação básica: divisão",
  KnjxWJTtmdU: "Aula de Literatura no Minecraft - Romantismo",
  bTCOUOZzFK4: "Aula de Astronomia no Minecraft - Astrofísica estelar",
  zBhyjJQQFak: "Aula de Física no Minecraft - Cinemática II",
  "1Qda_0oJ8v8": "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  "08SL4I9XXN4": "Aula de Matemática no Minecraft - Linguagem algébrica: grau de um polinômio",
  q99GeqBj7Uo: "Aula de Matemática no Minecraft - Geometria: retas paralelas",
  "vC6eETVu-BI": "Aula de Geografia no Minecraft - Permafrost e seus riscos",
  lW3nUUaGEk8: "Aula de Português no Minecraft",
  "pX7KjVIOq-w": "Aula de Português no Minecraft",
  "i84c1r-ZwVw": "Aula de Português no Minecraft",
  "o_iIsyVp-MM": "Aula de Matemática no Minecraft",
  z_UlmnD4_Zs: "Aula de Geografia no Minecraft",
  S4Sy5mrnjXY: "Aula de Física no Minecraft - Velocidade instantânea",
  RorjdBRZ49o: "Aula de Português no Minecraft",
  "3fLK6OtSPe4": "Aula de Química no Minecraft - Concentração comum e concentração molar",
  FpbJbOIe02o: "Aula de Ciências no Minecraft - O que é a luz?",
  xVyurRUHJ8A: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  XTu3C5dNbng: "Aula de História no Minecraft - Teoria da História",
  "-xljY5-iXj4": "Aula de Geografia no Minecraft - Geopolítica pós-2ª Guerra Mundial",
  "J3M-mkrgGes": "Aula de Matemática no Minecraft - O problema do castelo de 5 cômodos",
  "ioX-tNVZFo8": "Aula de Biologia no Minecraft - Características gerais dos seres vivos e níveis de organização (aula 2)",
  SYvu7yj1wuw: "Aula de Física no Minecraft - Quantidade de movimento",
  z8K3gzffqkc: "Aula de Geografia no Minecraft",
  "4UVFaWbwF18": "Aula de Português no Minecraft",
  nkW5QwYWLsw: "Aula de Matemática no Minecraft",
  QMJDYT3Id6E: "Aula de Astronomia no Minecraft - Estrelas de nêutrons e buracos negros",
  "9fQF3On1KJ4": "Aula de Xadrez no Minecraft",
  JoljBesfOPc: "Aula de Astronomia no Minecraft - Planeta Marte",
  YMTnY9AfJwk: "Aula de Geografia no Minecraft",
  DNS0pkkeKg4: "Aula de História no Minecraft - Surgimento do homem e do Estado",
  lqA9hzxhN9M: "Aula de História no Minecraft - Surgimento do homem e do Estado II",
  bxWVMycZ5V4: "Aula de História no Minecraft - Surgimento do homem e do Estado II",
  "XY0oZF-Qx_4": "Aula de Ciências no Minecraft - Processos reprodutivos: reprodução assexuada e sexuada",
  "3AySH-xTdFo": "Aula de Português no Minecraft",
  hIKWgiVLzWU: "Aula de Português no Minecraft",
  "5GkGdz7sq7M": "Aula de Astronomia no Minecraft - Planeta Mercúrio",
  "76gTsRimfu4": "Aula de Geografia no Minecraft",
  ZNOVIYllbb4: "Aula de Matemática no Minecraft - Equações de 1º e 2º grau",
  Fowyyh1d2n0: "Aula de Astronomia no Minecraft - Astrofísica e cosmologia",
  ruEfDDkNfVI: "Aula de Português no Minecraft",
  b1vTqKcN5pA: "Aula de Português no Minecraft",
  "46IZPmBbDT4": "Aula de Física no Minecraft - Energia nuclear",
  "-Bds3GXppWo": "Aula de Geografia no Minecraft",
  AWzdaT8zBZE: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  "lhp2pI-QYkY": "Aula de Matemática no Minecraft - Múltiplos e divisores: decomposição em fatores primos",
  tgNpZW0PcBA: "Aula de Português no Minecraft",
  ud6fGamSzeg: "Aula de Português no Minecraft",
  "w1-Q6ilg6OU": "Aula de Português no Minecraft",
  "3SHkKOYL6sA": "Aula de Geografia no Minecraft",
  Blp3_OQ7PAo: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  JoB7Ybmn1TA: "Aula de Astronomia no Minecraft - Gabarito comentado da OBA 2023 (nível 2)",
  rJLUwSFtkeM: "Aula de Português no Minecraft",
  CzM6wig7llk: "Aula de Português no Minecraft",
  LQH5TeLqZ6k: "Aula de Geografia no Minecraft",
  pgUOXBiLChc: "Aula de Inglês no Minecraft - Vocabulário, frases e quiz",
  NTRuUVRXrC8: "Aula de Matemática no Minecraft",
};
